/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#6f7973",
        "on-surface-variant": "#3f4944",
        "on-secondary-container": "#5c647a",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "#eff4ff",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "secondary": "#565e74",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#a6f2d1",
        "on-secondary": "#ffffff",
        "surface-tint": "#1b6b51",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-container": "#8bd6b7",
        "tertiary-fixed": "#d9e6dd",
        "on-tertiary-fixed-variant": "#3e4943",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#dae2fd",
        "tertiary": "#333f39",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002116",
        "on-tertiary-container": "#becac2",
        "surface-container": "#e5eeff",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#065f46",
        "on-primary-fixed-variant": "#00513b",
        "on-primary": "#ffffff",
        "inverse-surface": "#213145",
        "on-tertiary-fixed": "#131e19",
        "tertiary-fixed-dim": "#bdcac1",
        "outline-variant": "#bec9c2",
        "surface-container-high": "#dce9ff",
        "tertiary-container": "#4a564f",
        "background": "#f8f9ff",
        "primary": "#004532",
        "inverse-primary": "#8bd6b6",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#8bd6b6",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#131b2e"
      },
      fontFamily: {
        "hanken": ["Hanken Grotesk", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
      },
      borderRadius: {
        "default": "2px",
        "lg": "4px",
        "xl": "8px",
        "full": "12px",
      },
      spacing: {
        "gutter": "16px",
        "container-margin": "24px",
        "base": "8px",
        "section-gap": "40px"
      }
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
