// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appointments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of upcoming or past appointments for the current pet owner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Get Owner Appointments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter: 'upcoming' or 'past'",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointment.AppointmentListItem"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new appointment request for a pet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Create Appointment",
                "parameters": [
                    {
                        "description": "Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appointment.CreateAppointmentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/appointment.CreateAppointmentResponse"
                        }
                    }
                }
            }
        },
        "/appointments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get details of a specific appointment for the authenticated owner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Get Appointment Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/appointment.AppointmentDetailResponse"
                        }
                    }
                }
            }
        },
        "/fcm/token": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save or update the Firebase Cloud Messaging token for the current user session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Save FCM Token",
                "parameters": [
                    {
                        "description": "FCM Token Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SaveFCMTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove the Firebase Cloud Messaging token for the current user session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Delete FCM Token",
                "parameters": [
                    {
                        "description": "FCM Token Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.DeleteFCMTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of appointments for staff, with optional status, date, and doctor filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Get All Appointments (Internal)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment Status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Appointment Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter for doctor's own appointments",
                        "name": "my_appointments",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointment.AppointmentListItem"
                            }
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get comprehensive appointment information for staff members.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Get Internal Appointment Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/appointment.InternalAppointmentDetailResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}/approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accepts a new appointment request, moving it to 'Accepted' state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Approve Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}/doctor-approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transition an appointment from 'Waiting Doctor' to 'In Treatment' state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Doctor Approve Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}/doctor-reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rejects an assigned appointment, moving it back to 'Accepted' state for reassignment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Doctor Reject Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection Reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appointment.RejectAppointmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}/medical-record": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save physical examination, service-specific data, and reminders for an appointment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Save Medical Record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Medical Record Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appointment.SaveMedicalRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rejects a new appointment request with a provided reason.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Reject Appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection Reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appointment.RejectAppointmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/appointments/{id}/select-doctor": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Assign a specific doctor to an appointment that has been accepted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "summary": "Select Doctor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Appointment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Doctor ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appointment.SelectDoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/internal/login": {
            "post": {
                "description": "Login as a staff member (Manager, Receptionist, Doctor) using username and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login Internal",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginInternalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginInternalResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Invalidate the refresh token (from body or cookie) and clear the session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Logout Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.ActionResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the profile information of the currently authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Current Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.MeResponse"
                        }
                    }
                }
            }
        },
        "/owner/login": {
            "post": {
                "description": "Login as a pet owner using email and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login Owner",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginOwnerResponse"
                        }
                    }
                }
            }
        },
        "/owner/register": {
            "post": {
                "description": "Register a new account for a pet owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register Owner",
                "parameters": [
                    {
                        "description": "Registration Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterOwnerResponse"
                        }
                    }
                }
            }
        },
        "/pets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all pets owned by the currently authenticated pet owner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Get My Pets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pet.MyPetResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new pet under the currently authenticated pet owner's account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Create Pet",
                "parameters": [
                    {
                        "description": "Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pet.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pet.PetResponse"
                        }
                    }
                }
            }
        },
        "/pets/avatar/presigned-url": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a temporary presigned URL for secure avatar image upload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Get Presigned URL",
                "parameters": [
                    {
                        "description": "Presigned URL Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pet.GetPresignedURLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pet.GetPresignedURLResponse"
                        }
                    }
                }
            }
        },
        "/pets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detailed information about a specific pet owned by the current user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Get Pet Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pet.PetResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the profile information of an existing pet owned by the current user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Update Pet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pet.CreatePetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pet.PetResponse"
                        }
                    }
                }
            }
        },
        "/pets/{id}/appointments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all appointments for a specific pet owned by the current user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Get Pet Appointments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pet.PetAppointmentResponse"
                            }
                        }
                    }
                }
            }
        },
        "/pets/{id}/reminders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all reminders for a specific pet owned by the current user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Get Pet Reminders",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pet.PetReminderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/reminders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all active and unfulfilled reminders for all pets owned by the currently authenticated pet owner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reminder"
                ],
                "summary": "Get My Reminders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reminder.ReminderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/staff": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all staff members (Managers, Receptionists, Doctors).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Get Staff List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by activity status",
                        "name": "is_active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/staff.StaffResponse"
                            }
                        }
                    }
                }
            }
        },
        "/staff/doctor": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new internal user with the Doctor role and an associated doctor profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Create Doctor",
                "parameters": [
                    {
                        "description": "Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staff.CreateDoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/staff.CreateDoctorResponse"
                        }
                    }
                }
            }
        },
        "/staff/doctor/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get comprehensive information about a specific doctor, including professional profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Get Doctor Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Internal User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/staff.DoctorDetailResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the account details and professional profile of an existing doctor.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Update Doctor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Internal User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staff.UpdateDoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/staff.CreateDoctorResponse"
                        }
                    }
                }
            }
        },
        "/staff/doctors": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all staff members with the Doctor role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Get Doctor List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/staff.StaffResponse"
                            }
                        }
                    }
                }
            }
        },
        "/staff/receptionist": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new internal user with the Receptionist role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Create Receptionist",
                "parameters": [
                    {
                        "description": "Create Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staff.CreateReceptionistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/staff.CreateReceptionistResponse"
                        }
                    }
                }
            }
        },
        "/staff/receptionist/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get information about a specific receptionist account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Get Receptionist Detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Internal User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/staff.ReceptionistDetailResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the account details of an existing receptionist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Update Receptionist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Internal User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staff.UpdateReceptionistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/staff.CreateReceptionistResponse"
                        }
                    }
                }
            }
        },
        "/token/refresh": {
            "post": {
                "description": "Get a new access token using a valid refresh token (from body or cookie).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "appointment.AppointmentDetailPet": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointment.AppointmentDetailResponse": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "doctor": {
                    "$ref": "#/definitions/appointment.AppointmentDoctorSummary"
                },
                "id": {
                    "type": "string"
                },
                "medical_record": {
                    "$ref": "#/definitions/appointment.MedicalRecordResponse"
                },
                "owner_notes": {
                    "type": "string"
                },
                "pet": {
                    "$ref": "#/definitions/appointment.AppointmentDetailPet"
                },
                "previous_medical_history": {
                    "type": "string"
                },
                "service_type": {
                    "$ref": "#/definitions/models.ServiceType"
                },
                "status": {
                    "$ref": "#/definitions/models.AppointmentState"
                }
            }
        },
        "appointment.AppointmentDoctorSummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointment.AppointmentListItem": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pet": {
                    "$ref": "#/definitions/appointment.AppointmentPetSummary"
                },
                "service_type": {
                    "$ref": "#/definitions/models.ServiceType"
                },
                "status": {
                    "$ref": "#/definitions/models.AppointmentState"
                }
            }
        },
        "appointment.AppointmentOwnerSummary": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointment.AppointmentPetSummary": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointment.CheckupDetails": {
            "type": "object",
            "required": [
                "focus_area",
                "purpose"
            ],
            "properties": {
                "focus_area": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                }
            }
        },
        "appointment.CheckupMedicalDataDTO": {
            "type": "object",
            "required": [
                "cleanliness_notes",
                "palpation"
            ],
            "properties": {
                "cleanliness_notes": {
                    "type": "string"
                },
                "nutrition_recommendations": {
                    "type": "string"
                },
                "palpation": {
                    "type": "string"
                },
                "periodic_care_recommendations": {
                    "type": "string"
                }
            }
        },
        "appointment.CreateAppointmentRequest": {
            "type": "object",
            "required": [
                "appointment_date",
                "pet_id",
                "service_type"
            ],
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "checkup": {
                    "$ref": "#/definitions/appointment.CheckupDetails"
                },
                "owner_notes": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "integer"
                },
                "previous_medical_history": {
                    "type": "string"
                },
                "reminder_id": {
                    "type": "string"
                },
                "service_type": {
                    "enum": [
                        "vaccine",
                        "checkup",
                        "treatment"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ServiceType"
                        }
                    ]
                },
                "treatment": {
                    "$ref": "#/definitions/appointment.TreatmentDetails"
                },
                "vaccine": {
                    "$ref": "#/definitions/appointment.VaccineDetails"
                }
            }
        },
        "appointment.CreateAppointmentResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "appointment.InternalAppointmentDetailResponse": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "doctor": {
                    "$ref": "#/definitions/appointment.AppointmentDoctorSummary"
                },
                "id": {
                    "type": "string"
                },
                "medical_record": {
                    "$ref": "#/definitions/appointment.MedicalRecordResponse"
                },
                "owner": {
                    "$ref": "#/definitions/appointment.AppointmentOwnerSummary"
                },
                "owner_notes": {
                    "type": "string"
                },
                "pet": {
                    "$ref": "#/definitions/appointment.AppointmentDetailPet"
                },
                "previous_medical_history": {
                    "type": "string"
                },
                "service_type": {
                    "$ref": "#/definitions/models.ServiceType"
                },
                "status": {
                    "$ref": "#/definitions/models.AppointmentState"
                }
            }
        },
        "appointment.MedicalRecordResponse": {
            "type": "object",
            "properties": {
                "checkup": {
                    "$ref": "#/definitions/appointment.CheckupMedicalDataDTO"
                },
                "physical_examination": {
                    "$ref": "#/definitions/appointment.PhysicalExaminationDTO"
                },
                "treatment": {
                    "$ref": "#/definitions/appointment.TreatmentMedicalDataDTO"
                },
                "type": {
                    "$ref": "#/definitions/models.ServiceType"
                },
                "vaccine": {
                    "$ref": "#/definitions/appointment.VaccineMedicalDataDTO"
                }
            }
        },
        "appointment.PhysicalExaminationDTO": {
            "type": "object",
            "required": [
                "physical_condition",
                "temperature",
                "weight"
            ],
            "properties": {
                "heart_rate": {
                    "type": "string"
                },
                "physical_condition": {
                    "type": "string"
                },
                "respiratory_rate": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "appointment.PrescriptionDTO": {
            "type": "object",
            "required": [
                "dosage",
                "frequency",
                "name"
            ],
            "properties": {
                "dosage": {
                    "type": "string"
                },
                "frequency": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "appointment.RejectAppointmentRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "appointment.ReminderInputDTO": {
            "type": "object",
            "required": [
                "description",
                "reminder_date",
                "service_type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "reminder_date": {
                    "type": "string"
                },
                "service_type": {
                    "enum": [
                        "vaccine",
                        "checkup",
                        "treatment"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ServiceType"
                        }
                    ]
                }
            }
        },
        "appointment.SaveMedicalRecordRequest": {
            "type": "object",
            "required": [
                "physical_examination"
            ],
            "properties": {
                "checkup": {
                    "$ref": "#/definitions/appointment.CheckupMedicalDataDTO"
                },
                "physical_examination": {
                    "$ref": "#/definitions/appointment.PhysicalExaminationDTO"
                },
                "reminders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/appointment.ReminderInputDTO"
                    }
                },
                "treatment": {
                    "$ref": "#/definitions/appointment.TreatmentMedicalDataDTO"
                },
                "vaccine": {
                    "$ref": "#/definitions/appointment.VaccineMedicalDataDTO"
                }
            }
        },
        "appointment.SelectDoctorRequest": {
            "type": "object",
            "required": [
                "doctor_id"
            ],
            "properties": {
                "doctor_id": {
                    "type": "integer"
                }
            }
        },
        "appointment.TreatmentDetails": {
            "type": "object",
            "required": [
                "observed_symptoms",
                "symptom_duration"
            ],
            "properties": {
                "home_care_received": {
                    "type": "boolean"
                },
                "observed_symptoms": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "symptom_duration": {
                    "type": "string"
                }
            }
        },
        "appointment.TreatmentMedicalDataDTO": {
            "type": "object",
            "required": [
                "clinical_symptoms",
                "diagnosis",
                "estimated_cost",
                "medical_actions",
                "prescriptions"
            ],
            "properties": {
                "clinical_symptoms": {
                    "type": "string"
                },
                "diagnosis": {
                    "type": "string"
                },
                "estimated_cost": {
                    "type": "number",
                    "minimum": 0
                },
                "home_care_notes": {
                    "type": "string"
                },
                "medical_actions": {
                    "type": "string"
                },
                "prescriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/appointment.PrescriptionDTO"
                    }
                }
            }
        },
        "appointment.VaccineDetails": {
            "type": "object",
            "required": [
                "vaccine_type"
            ],
            "properties": {
                "vaccine_type": {
                    "type": "string"
                }
            }
        },
        "appointment.VaccineMedicalDataDTO": {
            "type": "object",
            "required": [
                "administration_date",
                "batch_number",
                "brand",
                "pre_vaccine_condition",
                "vaccine_type"
            ],
            "properties": {
                "administration_date": {
                    "type": "string"
                },
                "batch_number": {
                    "type": "string"
                },
                "brand": {
                    "type": "string"
                },
                "post_vaccine_reaction": {
                    "type": "string"
                },
                "pre_vaccine_condition": {
                    "type": "string"
                },
                "vaccine_type": {
                    "type": "string"
                }
            }
        },
        "auth.DeleteFCMTokenRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.LoginInternalRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.LoginInternalResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "string"
                }
            }
        },
        "auth.LoginOwnerRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.LoginOwnerResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "string"
                }
            }
        },
        "auth.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth.MeResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/models.AccountRole"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterOwnerRequest": {
            "type": "object",
            "required": [
                "email",
                "full_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "auth.RegisterOwnerResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "auth.SaveFCMTokenRequest": {
            "type": "object",
            "required": [
                "device_type",
                "token"
            ],
            "properties": {
                "device_type": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "core.ActionResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.AccountRole": {
            "type": "string",
            "enum": [
                "manager",
                "receptionist",
                "doctor",
                "owner"
            ],
            "x-enum-varnames": [
                "RoleManager",
                "RoleReceptionist",
                "RoleDoctor",
                "RoleOwner"
            ]
        },
        "models.AppointmentState": {
            "type": "string",
            "enum": [
                "Menunggu Konfirmasi",
                "Diterima",
                "Ditolak",
                "Menunggu Dokter",
                "Dalam Penanganan",
                "Selesai",
                "Selesai Administrasi"
            ],
            "x-enum-varnames": [
                "StateWaitingConfirmation",
                "StateAccepted",
                "StateRejected",
                "StateWaitingDoctor",
                "StateInTreatment",
                "StateFinished",
                "StateAdminFinished"
            ]
        },
        "models.Gender": {
            "type": "string",
            "enum": [
                "male",
                "female"
            ],
            "x-enum-varnames": [
                "GenderMale",
                "GenderFemale"
            ]
        },
        "models.ServiceType": {
            "type": "string",
            "enum": [
                "vaccine",
                "checkup",
                "treatment"
            ],
            "x-enum-varnames": [
                "ServiceTypeVaccine",
                "ServiceTypeCheckup",
                "ServiceTypeTreatment"
            ]
        },
        "pet.CreatePetRequest": {
            "type": "object",
            "required": [
                "birth_date",
                "breed",
                "gender",
                "name",
                "species"
            ],
            "properties": {
                "avatar_upload_id": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "gender": {
                    "enum": [
                        "male",
                        "female"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Gender"
                        }
                    ]
                },
                "initial_medical_history": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "species": {
                    "type": "string"
                }
            }
        },
        "pet.GetPresignedURLRequest": {
            "type": "object",
            "required": [
                "content_type",
                "file_size"
            ],
            "properties": {
                "content_type": {
                    "type": "string",
                    "enum": [
                        "image/jpeg",
                        "image/png",
                        "image/webp"
                    ]
                },
                "file_size": {
                    "description": "Max 5MB",
                    "type": "integer",
                    "maximum": 5242880,
                    "minimum": 1
                }
            }
        },
        "pet.GetPresignedURLResponse": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "upload_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pet.MyPetResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "species": {
                    "type": "string"
                }
            }
        },
        "pet.PetAppointmentResponse": {
            "type": "object",
            "properties": {
                "appointment_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "service_type": {
                    "$ref": "#/definitions/models.ServiceType"
                },
                "status": {
                    "$ref": "#/definitions/models.AppointmentState"
                }
            }
        },
        "pet.PetReminderResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "service_type": {
                    "$ref": "#/definitions/models.ServiceType"
                }
            }
        },
        "pet.PetResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/models.Gender"
                },
                "id": {
                    "type": "integer"
                },
                "initial_medical_history": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "species": {
                    "type": "string"
                }
            }
        },
        "reminder.PetResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "reminder.ReminderResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pet": {
                    "$ref": "#/definitions/reminder.PetResponse"
                },
                "service_type": {
                    "$ref": "#/definitions/models.ServiceType"
                }
            }
        },
        "staff.CreateDoctorRequest": {
            "type": "object",
            "required": [
                "birth_date",
                "education_history",
                "full_name",
                "join_date",
                "password",
                "practice_location_history",
                "practice_start_date",
                "username"
            ],
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "education_history": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "is_active": {
                    "type": "boolean"
                },
                "join_date": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "practice_location_history": {
                    "type": "string"
                },
                "practice_start_date": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 4
                }
            }
        },
        "staff.CreateDoctorResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "staff.CreateReceptionistRequest": {
            "type": "object",
            "required": [
                "full_name",
                "password",
                "username"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "is_active": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 4
                }
            }
        },
        "staff.CreateReceptionistResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "staff.DoctorDetailResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "education_history": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "join_date": {
                    "type": "string"
                },
                "practice_location_history": {
                    "type": "string"
                },
                "practice_start_date": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.AccountRole"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "staff.ReceptionistDetailResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "role": {
                    "$ref": "#/definitions/models.AccountRole"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "staff.StaffResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/models.AccountRole"
                }
            }
        },
        "staff.UpdateDoctorRequest": {
            "type": "object",
            "required": [
                "birth_date",
                "education_history",
                "full_name",
                "join_date",
                "practice_location_history",
                "practice_start_date"
            ],
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "education_history": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "is_active": {
                    "type": "boolean"
                },
                "join_date": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "practice_location_history": {
                    "type": "string"
                },
                "practice_start_date": {
                    "type": "string"
                }
            }
        },
        "staff.UpdateReceptionistRequest": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 255
                },
                "is_active": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "VetConnect API",
	Description:      "API for VetConnect Clinic Management System.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
