substitutions:
  _REPO_NAME: "vetconnect"
  _IMAGE_NAME: "vetconnect-server"
  _SERVICE_NAME: "vetconnect-server"

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Image"
    args:
      - "build"
      - "-t"
      - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA"
      - "./server"

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Image"
    args:
      - "push"
      - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA"
      - "--region"
      - "asia-southeast2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
